'use client';

import React from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/Card';
import { Download, Share2, Info, CheckCircle, Shield } from 'lucide-react';

const DataPortability = () => {
  return (
    <div className="p-4 md:p-8 md:ml-64 pb-20 md:pb-8 max-w-4xl">
      <header className="mb-8">
        <h2 className="text-3xl font-bold">Data & Privacy</h2>
        <p className="text-gray-500">Your data, your control.</p>
      </header>

      <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-12">
        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2 text-purple-600">
                    <Download size={20} /> Export Your Data
                </CardTitle>
            </CardHeader>
            <CardContent>
                <p className="text-sm text-gray-500 mb-6">Switching apps or need a spreadsheet for your parents? Download your entire history here.</p>
                <div className="flex gap-3">
                    <button className="flex-1 bg-gray-50 hover:bg-gray-100 py-3 rounded-xl font-bold text-xs">Download CSV</button>
                    <button className="flex-1 bg-gray-50 hover:bg-gray-100 py-3 rounded-xl font-bold text-xs">Download JSON</button>
                </div>
            </CardContent>
        </Card>

        <Card>
            <CardHeader>
                <CardTitle className="flex items-center gap-2 text-blue-600">
                    <CheckCircle size={20} /> Data Transparency
                </CardTitle>
            </CardHeader>
            <CardContent className="space-y-4">
                <div className="flex gap-3 items-start">
                    <Shield size={18} className="text-green-600 shrink-0 mt-1" />
                    <div>
                        <p className="font-bold text-sm">We never sell your data</p>
                        <p className="text-[10px] text-gray-400">Your transactions are for your eyes only.</p>
                    </div>
                </div>
                <div className="flex gap-3 items-start">
                    <Shield size={18} className="text-green-600 shrink-0 mt-1" />
                    <div>
                        <p className="font-bold text-sm">Read-only Bank Access</p>
                        <p className="text-[10px] text-gray-400">We cannot move money out of your account.</p>
                    </div>
                </div>
            </CardContent>
        </Card>
      </div>

      <div className="p-8 bg-red-50 border border-red-100 rounded-3xl">
        <h4 className="text-red-900 font-bold mb-2">The Disclaimer Layer</h4>
        <p className="text-red-700 text-sm leading-relaxed">
            Allowee is a financial tracking tool, not a licensed financial advisor. The "Spend Plans" generated by our AI agents are educational simulations based on school marketplace data and are not professional financial advice.
        </p>
      </div>
    </div>
  );
};

export default DataPortability;
