'use client';

import React from 'react';

const LegalPage = ({ title }: { title: string }) => (
    <div className="p-4 md:p-8 md:ml-64 pb-20 md:pb-8 max-w-3xl">
        <h2 className="text-3xl font-bold mb-8">{title}</h2>
        <div className="prose prose-purple bg-white p-8 rounded-3xl border border-gray-100 space-y-6 text-gray-600">
            <section>
                <h3 className="text-xl font-bold text-gray-900 mb-2">1. Introduction</h3>
                <p>Welcome to Allowee. By using our application, you agree to our terms and conditions. We are committed to helping Nigerian students manage their finances better.</p>
            </section>
            <section>
                <h3 className="text-xl font-bold text-gray-900 mb-2">2. Data Privacy</h3>
                <p>We do not sell your personal financial data to third parties. Your transaction history is encrypted and used only to provide you with budgeting insights.</p>
            </section>
            <section>
                <h3 className="text-xl font-bold text-gray-900 mb-2">3. Not Financial Advice</h3>
                <p>The Spend Plans generated by Allowee are for educational purposes only. Always consult with a professional for serious financial decisions.</p>
            </section>
        </div>
    </div>
);

export const PrivacyPolicy = () => <LegalPage title="Privacy Policy" />;
export const TermsOfService = () => <LegalPage title="Terms of Service" />;

export default LegalPage;
